services:
  mysql:
    image: 'mysql:8.0.46-debian'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    ports:
      - '3306:3306'

    volumes:
      - jb_api_mysql_data:/var/lib/mysql

volumes:
  jb_api_mysql_data: