spring:
  application:
    name: james-bond-movies-api

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  jackson:
    property-naming-strategy: SNAKE_CASE

# DEBUG logging is only viable in a testing environment
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.schema: DEBUG
