spring:
  application:
    name: james-bond-movies-api

  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8mb4

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  jackson:
    property-naming-strategy: SNAKE_CASE

# DEBUG logging is only viable in a testing environment
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.schema: DEBUG
    org:
      flywaydb: DEBUG
    db:
      migration: DEBUG
    com.zaxxer.hikari: DEBUG
    com.mysql.cj: DEBUG
