-- Insert genre tags
INSERT INTO genres (id, title, created_at, updated_at)
VALUES (
    UUID_TO_BIN('5c9e7894-3981-4505-97d7-3aca977b2264'),
    'Action',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
),(
    UUID_TO_BIN('73281816-9ffb-4763-bd33-cec826d7bbdb'),
    'Adventure',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
),(
    UUID_TO_BIN('c57fc19d-82ad-4410-aa32-3f78d7a30cc9'),
    'Thriller',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
),(
    UUID_TO_BIN('bcef13c7-7861-40ac-bd4d-b7634dbeef49'),
    'Spy',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
),(
    UUID_TO_BIN('d96243b4-0e9f-4e43-94b2-87933ca8df77'),
    'Sci-Fi',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
),(
    UUID_TO_BIN('7bbaf6fc-ddd5-40cf-b5a1-f281a2e22433'),
    'Mystery',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
),(
    UUID_TO_BIN('b5266995-003f-490b-8fdb-1bc57fbedcfe'),
    'Heist',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
),(
    UUID_TO_BIN('a26e5f5c-f6c6-4f23-87bc-26ba3dff1b1d'),
    'Drama',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
),(
    UUID_TO_BIN('93cb3a8c-8a07-4785-a13f-d539583eabd8'),
    'Comedy',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
),(
    UUID_TO_BIN('36d38fb1-ac5f-443c-b45c-e50f3635e002'),
    'Romance',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
),(
    UUID_TO_BIN('bb1d9d29-74a2-4d5b-98f6-0f7016170c9f'),
    'Psychological',
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
);

/**
  Add genres to every movie using the join table
 */

INSERT INTO movies_genres (movie_id, genre_id)
VALUES
    ((SELECT id FROM movies WHERE title = 'Dr. No'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Dr. No'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'Dr. No'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Dr. No'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Dr. No'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'From Russia With Love'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'From Russia With Love'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'From Russia With Love'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'From Russia With Love'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'From Russia With Love'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'Goldfinger'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Goldfinger'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Goldfinger'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Goldfinger'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Goldfinger'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'Goldfinger'), (SELECT id FROM genres WHERE title = 'Heist')),
    ((SELECT id FROM movies WHERE title = 'Thunderball'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Thunderball'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Thunderball'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Thunderball'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'You Only Live Twice'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'You Only Live Twice'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'You Only Live Twice'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'You Only Live Twice'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'You Only Live Twice'), (SELECT id FROM genres WHERE title = 'Sci-Fi')),
    ((SELECT id FROM movies WHERE title = 'You Only Live Twice'), (SELECT id FROM genres WHERE title = 'Romance')),
    ((SELECT id FROM movies WHERE title = 'On Her Majesty''s Secret Service'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'On Her Majesty''s Secret Service'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'On Her Majesty''s Secret Service'), (SELECT id FROM genres WHERE title = 'Romance')),
    ((SELECT id FROM movies WHERE title = 'On Her Majesty''s Secret Service'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'On Her Majesty''s Secret Service'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'On Her Majesty''s Secret Service'), (SELECT id FROM genres WHERE title = 'Drama')),
    ((SELECT id FROM movies WHERE title = 'Diamonds Are Forever'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Diamonds Are Forever'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Diamonds Are Forever'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Diamonds Are Forever'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Diamonds Are Forever'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'Diamonds Are Forever'), (SELECT id FROM genres WHERE title = 'Heist')),
    ((SELECT id FROM movies WHERE title = 'Live And Let Die'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Live And Let Die'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Live And Let Die'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Live And Let Die'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Live And Let Die'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'The Man With The Golden Gun'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'The Man With The Golden Gun'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'The Man With The Golden Gun'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'The Man With The Golden Gun'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'The Man With The Golden Gun'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'The Spy Who Loved Me'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'The Spy Who Loved Me'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'The Spy Who Loved Me'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'The Spy Who Loved Me'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'The Spy Who Loved Me'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'The Spy Who Loved Me'), (SELECT id FROM genres WHERE title = 'Sci-Fi')),
    ((SELECT id FROM movies WHERE title = 'Moonraker'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Moonraker'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Moonraker'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Moonraker'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Moonraker'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'Moonraker'), (SELECT id FROM genres WHERE title = 'Sci-Fi')),
    ((SELECT id FROM movies WHERE title = 'For Your Eyes Only'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'For Your Eyes Only'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'For Your Eyes Only'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'For Your Eyes Only'), (SELECT id FROM genres WHERE title = 'Drama')),
    ((SELECT id FROM movies WHERE title = 'For Your Eyes Only'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'For Your Eyes Only'), (SELECT id FROM genres WHERE title = 'Heist')),
    ((SELECT id FROM movies WHERE title = 'Octopussy'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Octopussy'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Octopussy'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Octopussy'), (SELECT id FROM genres WHERE title = 'Heist')),
    ((SELECT id FROM movies WHERE title = 'Octopussy'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Octopussy'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'Octopussy'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'A View To A Kill'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'A View To A Kill'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'A View To A Kill'), (SELECT id FROM genres WHERE title = 'Heist')),
    ((SELECT id FROM movies WHERE title = 'A View To A Kill'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'A View To A Kill'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'A View To A Kill'), (SELECT id FROM genres WHERE title = 'Romance')),
    ((SELECT id FROM movies WHERE title = 'A View To A Kill'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'The Living Daylights'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'The Living Daylights'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'The Living Daylights'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'The Living Daylights'), (SELECT id FROM genres WHERE title = 'Drama')),
    ((SELECT id FROM movies WHERE title = 'The Living Daylights'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'The Living Daylights'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'License To Kill'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'License To Kill'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'License To Kill'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'License To Kill'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'License To Kill'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'Goldeneye'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Goldeneye'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Goldeneye'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Goldeneye'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Goldeneye'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'Goldeneye'), (SELECT id FROM genres WHERE title = 'Heist')),
    ((SELECT id FROM movies WHERE title = 'Goldeneye'), (SELECT id FROM genres WHERE title = 'Sci-Fi')),
    ((SELECT id FROM movies WHERE title = 'Goldeneye'), (SELECT id FROM genres WHERE title = 'Romance')),
    ((SELECT id FROM movies WHERE title = 'Goldeneye'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'Tomorrow Never Dies'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Tomorrow Never Dies'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Tomorrow Never Dies'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Tomorrow Never Dies'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Tomorrow Never Dies'), (SELECT id FROM genres WHERE title = 'Romance')),
    ((SELECT id FROM movies WHERE title = 'The World Is Not Enough'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'The World Is Not Enough'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'The World Is Not Enough'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'The World Is Not Enough'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'The World Is Not Enough'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'The World Is Not Enough'), (SELECT id FROM genres WHERE title = 'Psychological')),
    ((SELECT id FROM movies WHERE title = 'The World Is Not Enough'), (SELECT id FROM genres WHERE title = 'Drama')),
    ((SELECT id FROM movies WHERE title = 'Die Another Day'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Die Another Day'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Die Another Day'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Die Another Day'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Die Another Day'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'Die Another Day'), (SELECT id FROM genres WHERE title = 'Psychological')),
    ((SELECT id FROM movies WHERE title = 'Die Another Day'), (SELECT id FROM genres WHERE title = 'Drama')),
    ((SELECT id FROM movies WHERE title = 'Casino Royale'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Casino Royale'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Casino Royale'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Casino Royale'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Casino Royale'), (SELECT id FROM genres WHERE title = 'Heist')),
    ((SELECT id FROM movies WHERE title = 'Casino Royale'), (SELECT id FROM genres WHERE title = 'Romance')),
    ((SELECT id FROM movies WHERE title = 'Casino Royale'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'Casino Royale'), (SELECT id FROM genres WHERE title = 'Psychological')),
    ((SELECT id FROM movies WHERE title = 'Quantum Of Solace'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Quantum Of Solace'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Quantum Of Solace'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Quantum Of Solace'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Quantum Of Solace'), (SELECT id FROM genres WHERE title = 'Psychological')),
    ((SELECT id FROM movies WHERE title = 'Quantum Of Solace'), (SELECT id FROM genres WHERE title = 'Drama')),
    ((SELECT id FROM movies WHERE title = 'Quantum Of Solace'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'Skyfall'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Skyfall'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Skyfall'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Skyfall'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Skyfall'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'Skyfall'), (SELECT id FROM genres WHERE title = 'Romance')),
    ((SELECT id FROM movies WHERE title = 'Skyfall'), (SELECT id FROM genres WHERE title = 'Comedy')),
    ((SELECT id FROM movies WHERE title = 'Skyfall'), (SELECT id FROM genres WHERE title = 'Psychological')),
    ((SELECT id FROM movies WHERE title = 'Skyfall'), (SELECT id FROM genres WHERE title = 'Drama')),
    ((SELECT id FROM movies WHERE title = 'Spectre'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'Spectre'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'Spectre'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'Spectre'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'Spectre'), (SELECT id FROM genres WHERE title = 'Drama')),
    ((SELECT id FROM movies WHERE title = 'Spectre'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'Spectre'), (SELECT id FROM genres WHERE title = 'Psychological')),
    ((SELECT id FROM movies WHERE title = 'Spectre'), (SELECT id FROM genres WHERE title = 'Romance')),
    ((SELECT id FROM movies WHERE title = 'No Time To Die'), (SELECT id FROM genres WHERE title = 'Action')),
    ((SELECT id FROM movies WHERE title = 'No Time To Die'), (SELECT id FROM genres WHERE title = 'Adventure')),
    ((SELECT id FROM movies WHERE title = 'No Time To Die'), (SELECT id FROM genres WHERE title = 'Thriller')),
    ((SELECT id FROM movies WHERE title = 'No Time To Die'), (SELECT id FROM genres WHERE title = 'Spy')),
    ((SELECT id FROM movies WHERE title = 'No Time To Die'), (SELECT id FROM genres WHERE title = 'Romance')),
    ((SELECT id FROM movies WHERE title = 'No Time To Die'), (SELECT id FROM genres WHERE title = 'Mystery')),
    ((SELECT id FROM movies WHERE title = 'No Time To Die'), (SELECT id FROM genres WHERE title = 'Sci-Fi')),
    ((SELECT id FROM movies WHERE title = 'No Time To Die'), (SELECT id FROM genres WHERE title = 'Drama'));
